export default {
  bigStat: [
    {
      product: '收入详细',
      total: '4,232',
      color: 'primary',
      registrations: {
        value: 830,
        profit: true,
      },
      bounce: {
        value: 4.5,
        profit: false,
      },
    },
    {
      product: '支出详细',
      total: '754',
      color: 'danger',
      registrations: {
        value: 30,
        profit: true,
      },
      bounce: {
        value: 2.5,
        profit: true,
      },
    },
    {
      product: '利润',
      total: '1,025',
      color: 'info',
      registrations: {
        value: 230,
        profit: true,
      },
      bounce: {
        value: 21.5,
        profit: false,
      },
    },
  ],
  table: [
    {
      id: 0,
      name: '哈哈哈有限垄断公司',
      email: '天天银行',
      product: '本公司垄断全球哈哈哈产品',
      price: '￥1.2',
      date: '5/11/2017',
      city: '上海',
      status: '已发送',
    },
    {
      id: 1,
      name: '廣東嘿嘿嘿有限股份公司',
      email: 'thornton@wxample.com',
      product: '你無使猜啦，又猜無倒葛良心產品',
      price: '$1 254.2',
      date: '4 Jun 2017',
      city: 'HK',
      status: 'Sent',
    },
    {
      id: 2,
      name: 'Economy-HK',
      email: 'bird@wxample.com',
      product: '快滴揾一揾你身邊個ECONOMY啦~裏斗都有你中意個產品o',
      price: '$1 570.0',
      date: '27 Aug 2017',
      city: 'Leadville North',
      status: 'Pending',
    },
    {
      id: 3,
      name: 'Joseph May',
      email: 'josephmay@wxample.com',
      product: 'Version Control',
      price: '$5 224.5',
      date: '19 Feb 2018',
      city: 'Seaforth',
      status: 'Declined',
    },
    {
      id: 4,
      name: 'Peter Horadnia',
      email: 'horadnia@wxample.com',
      product: 'Let\'s Dance',
      price: '$43 594.7',
      date: '1 Mar 2018',
      city: 'Hanoverton',
      status: 'Sent',
    },
  ],
};
